name: CI
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Lint
      run: |
        npm i
        npm run lint -- --max-warnings 0

  betterer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Check if code became worse
      run: |
        npm i
        npm run betterer ci
